# Generated by Django 2.2.6 on 2019-10-08 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='depart',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
