# Generated by Django 2.2.6 on 2019-10-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_depart_is_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depart',
            name='c_time',
            field=models.DateField(verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='depart',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='逻辑删除'),
        ),
    ]
