# Generated by Django 2.2.6 on 2019-10-25 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('name', models.CharField(max_length=30, verbose_name='讲师姓名')),
                ('avatar_url', models.URLField(default='', verbose_name='头像url')),
                ('profession', models.CharField(max_length=50, verbose_name='职称')),
                ('profile', models.CharField(max_length=300, verbose_name='讲师简介')),
            ],
            options={
                'verbose_name': '讲师',
                'verbose_name_plural': '讲师',
                'db_table': 'tb_teachers',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('name', models.CharField(max_length=200, verbose_name='课程名称')),
                ('cover_url', models.URLField(default='', verbose_name='课程封面url')),
                ('video_url', models.URLField(default='', verbose_name='课程视频url')),
                ('introduce', models.CharField(max_length=200, verbose_name='课程简介')),
                ('outline', models.CharField(max_length=300, verbose_name='课程大纲')),
                ('file_id', models.CharField(max_length=30, verbose_name='课程视频id')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Teacher', verbose_name='课程讲师')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
                'db_table': 'tb_courses',
            },
        ),
    ]
