# Generated by Django 2.2.6 on 2019-10-24 04:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('file_url', models.URLField(help_text='文档url', verbose_name='文档url')),
                ('title', models.CharField(help_text='文档蒙城', max_length=200, verbose_name='文档名称')),
                ('desc', models.TextField(help_text='文档描述', validators=[django.core.validators.MaxLengthValidator(200), django.core.validators.MinLengthValidator(1)], verbose_name='文档描述')),
                ('image_url', models.URLField(default='', help_text='文档封面url', verbose_name='文档封面url')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='文档上传者')),
            ],
            options={
                'verbose_name': '文档',
                'verbose_name_plural': '文档',
                'db_table': 'tb_docs',
            },
        ),
    ]
